=== Anto1911/labs/Shilpa/labs/src/main/webapp/WEB-INF/users.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.shilpademo.com/labs"
           xmlns="http://www.shilpademo.com/labs"
           elementFormDefault="qualified">
  
  <xs:simpleType name="IDFormat">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{6}" />
        </xs:restriction>
   </xs:simpleType>
    
  <xs:simpleType name="nameFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-z]+[\s])+[A-Z][a-z]*" />
        </xs:restriction>
  </xs:simpleType>
    
  <xs:simpleType name="emailFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_%+-]+[.][a-zA-Z0-9_%+-]+@[a-zA-Z0-9-]+(.com)" />
        </xs:restriction>
  </xs:simpleType> 
    
  <xs:simpleType name="passwordFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-za-z]{5,}\d{2,}" />
        </xs:restriction>
  </xs:simpleType> 
    
  <xs:simpleType name="dobFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{2}-\d{2}" />
        </xs:restriction>
  </xs:simpleType>
    
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="IDFormat" name="ID"/>
              <xs:element type="nameFormat" name="name"/>                   
              <xs:element type="emailFormat" name="email"/>
              <xs:element type="passwordFormat" name="password"/>
              <xs:element type="dobFormat" name="DOB"/> 
            </xs:sequence>
          </xs:complexType>
          
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Anto1911/labs/Shilpa/labs/src/main/webapp/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XSL/users.xsl"?>

<!--<users xmlns="http://www.shilpademo.com/labs"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.shilpademo.com/labs users.xsd">-->
  <users>
    <user>
        <ID>608493</ID>
        <name>Alice Ming</name>
        <email>alice.m@example.com</email>
        <password>Helloworld222</password>
        <DOB>1999-03-02</DOB>        
    </user>
    <user>
        <ID>608500</ID>
        <name>Shilpa G</name>
        <email>shilpa.g@example.com</email>
        <password>Helloo123</password>
        <DOB>1991-09-30</DOB>        
    </user>
    <user>
        <ID>100129</ID>
        <name>John Smith</name>
        <email>john.smith@uts.com</email>
        <password>Helloo123</password>
        <DOB>2000-12-30</DOB>        
    </user>
    <user>
        <ID>100129</ID>
        <name>Alex Jones</name>
        <email>alex.jones@abdc.com</email>
        <password>Helloo123</password>
        <DOB>1996-06-06</DOB>        
    </user>
</users>
